
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: vladtodorchuk
  password: 6975

development:
  <<: *default
  database: to_do_api_development

test:
  <<: *default
  database: to_do_api_test

production:
  <<: *default
  database: to_do_api_production
